name: dart_topsis
description: Aplicativo de linha de comando TOPSIS.
version: 1.0.0

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  csv: ^5.0.1
  tabular: ^0.6.3+1
  args: ^2.3.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
